name: Build Windows Kyty

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Windows Derlemesi
        run: |
          .\build-windows.cmd

      - name: Dosyalari Yukle
        uses: actions/upload-artifact@v4
        with:
          name: kytyps5-windows-binaries
          path: |
            _Build/windows/
            *.exe
